services:
  - type: web
    name: company-management-system
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9  # Use 3.11 instead of 3.13 for better compatibility